from typing import List, Dict, Any

class AnswerBuilder:
    def __init__(self):
        pass

    def construct_final_answer(self, context: List[Dict[str, Any]], generated_response: str) -> Dict[str, Any]:
        """
        Construct the final answer from the retrieved context and generated response.
        
        Parameters:
        - context: A list of documents or chunks of text that provide context for the answer.
        - generated_response: The response generated by the model based on the context.

        Returns:
        A dictionary containing the final answer and source attribution.
        """
        if not context:
            return {
                "final_answer": generated_response,
                "sources": []
            }

        # Extract source information from the context
        sources = [item.get("source_path", "Unknown source") for item in context]

        # Construct the final answer
        final_answer = f"{generated_response}\n\nSources:\n" + "\n".join(sources)

        return {
            "final_answer": final_answer,
            "sources": sources
        }